### ISSUE TITLE
Unexpected length of decoded output

### ISSUE THREAD

**Issue by ykchong45** [xukmin/viterbi#1]
I tested your example and it gives me a 15-bit output. Since the encoded data is 34-bit long and there are 2 polynomials (011 and 101 in your example), I guess the output should be 34/2=17-bit.

> Test code: `./viterbi_main 3 7 5 0011100001100111111000101100111011`
> Return: `010111001010001`

**Comment by xukmin** [comment]
When encoding a message, there are always (constraint - 1) "0" bits padded in front. So in your case, given constraint = 3, # polynomials = 2, and length of encoded message = 34, length of the original message is 34 / 2 - (3 - 1) = 15.

You can also verify the output is correct by encoding it again:

```bash
$ ./viterbi_main 3 7 5 --encode 010111001010001
0011100001100111111000101100111011
```
